name: jest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm test
